package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.AspCtripMapping;
import com.ctrip.asp.commom.dao.auto.model.AspCtripMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspCtripMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(AspCtripMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(AspCtripMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(AspCtripMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(AspCtripMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<AspCtripMapping> selectByExample(AspCtripMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    AspCtripMapping selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") AspCtripMapping record, @Param("example") AspCtripMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") AspCtripMapping record, @Param("example") AspCtripMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(AspCtripMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(AspCtripMapping record);
}