package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.AspStatistics;
import com.ctrip.asp.commom.dao.auto.model.AspStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AspStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(AspStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(AspStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(AspStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(AspStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<AspStatistics> selectByExample(AspStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    AspStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") AspStatistics record, @Param("example") AspStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") AspStatistics record, @Param("example") AspStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(AspStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(AspStatistics record);
}