package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.HotelBooking;
import com.ctrip.asp.commom.dao.auto.model.HotelBookingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelBookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(HotelBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(HotelBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(HotelBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(HotelBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<HotelBooking> selectByExample(HotelBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    HotelBooking selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") HotelBooking record, @Param("example") HotelBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") HotelBooking record, @Param("example") HotelBookingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(HotelBooking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_booking
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(HotelBooking record);
}