package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.InInvoicenotifyLog;
import com.ctrip.asp.commom.dao.auto.model.InInvoicenotifyLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InInvoicenotifyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(InInvoicenotifyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(InInvoicenotifyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(InInvoicenotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(InInvoicenotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<InInvoicenotifyLog> selectByExample(InInvoicenotifyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    InInvoicenotifyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") InInvoicenotifyLog record, @Param("example") InInvoicenotifyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") InInvoicenotifyLog record, @Param("example") InInvoicenotifyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(InInvoicenotifyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicenotify_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(InInvoicenotifyLog record);
}