package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.InInvoicebookingLog;
import com.ctrip.asp.commom.dao.auto.model.InInvoicebookingLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InInvoicebookingLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(InInvoicebookingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(InInvoicebookingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(InInvoicebookingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(InInvoicebookingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<InInvoicebookingLog> selectByExample(InInvoicebookingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    InInvoicebookingLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") InInvoicebookingLog record, @Param("example") InInvoicebookingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") InInvoicebookingLog record, @Param("example") InInvoicebookingLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(InInvoicebookingLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicebooking_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(InInvoicebookingLog record);
}