package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.InInvoicetranssearchRsLog;
import com.ctrip.asp.commom.dao.auto.model.InInvoicetranssearchRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InInvoicetranssearchRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(InInvoicetranssearchRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(InInvoicetranssearchRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<InInvoicetranssearchRsLog> selectByExampleWithBLOBs(InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<InInvoicetranssearchRsLog> selectByExample(InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") InInvoicetranssearchRsLog record, @Param("example") InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") InInvoicetranssearchRsLog record, @Param("example") InInvoicetranssearchRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicetransSearch_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") InInvoicetranssearchRsLog record, @Param("example") InInvoicetranssearchRsLogExample example);
}