package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapHotelInfo;
import com.ctrip.asp.commom.dao.auto.model.MapHotelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapHotelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapHotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapHotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapHotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapHotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapHotelInfo> selectByExample(MapHotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapHotelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapHotelInfo record, @Param("example") MapHotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapHotelInfo record, @Param("example") MapHotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapHotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_hotel_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapHotelInfo record);
}