package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildDoor;
import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildDoorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapRoomBuildDoorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapRoomBuildDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapRoomBuildDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapRoomBuildDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapRoomBuildDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapRoomBuildDoor> selectByExample(MapRoomBuildDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapRoomBuildDoor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapRoomBuildDoor record, @Param("example") MapRoomBuildDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapRoomBuildDoor record, @Param("example") MapRoomBuildDoorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapRoomBuildDoor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_door
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapRoomBuildDoor record);
}