package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildRoom;
import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildRoomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapRoomBuildRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapRoomBuildRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapRoomBuildRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapRoomBuildRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapRoomBuildRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapRoomBuildRoom> selectByExample(MapRoomBuildRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapRoomBuildRoom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapRoomBuildRoom record, @Param("example") MapRoomBuildRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapRoomBuildRoom record, @Param("example") MapRoomBuildRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapRoomBuildRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_room
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapRoomBuildRoom record);
}