package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildApdt;
import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildApdtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapRoomBuildApdtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapRoomBuildApdtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapRoomBuildApdtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapRoomBuildApdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapRoomBuildApdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapRoomBuildApdt> selectByExample(MapRoomBuildApdtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapRoomBuildApdt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapRoomBuildApdt record, @Param("example") MapRoomBuildApdtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapRoomBuildApdt record, @Param("example") MapRoomBuildApdtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapRoomBuildApdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_apdt
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapRoomBuildApdt record);
}