package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildCon;
import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildConExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapRoomBuildConMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapRoomBuildConExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapRoomBuildConExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapRoomBuildCon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapRoomBuildCon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapRoomBuildCon> selectByExample(MapRoomBuildConExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapRoomBuildCon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapRoomBuildCon record, @Param("example") MapRoomBuildConExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapRoomBuildCon record, @Param("example") MapRoomBuildConExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapRoomBuildCon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_con
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapRoomBuildCon record);
}