package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildFloor;
import com.ctrip.asp.commom.dao.auto.model.MapRoomBuildFloorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MapRoomBuildFloorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(MapRoomBuildFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(MapRoomBuildFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(MapRoomBuildFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(MapRoomBuildFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<MapRoomBuildFloor> selectByExample(MapRoomBuildFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    MapRoomBuildFloor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") MapRoomBuildFloor record, @Param("example") MapRoomBuildFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") MapRoomBuildFloor record, @Param("example") MapRoomBuildFloorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(MapRoomBuildFloor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map_room_build_floor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(MapRoomBuildFloor record);
}