package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrHotelRoomInfo;
import com.ctrip.asp.commom.dao.auto.model.SrHotelRoomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrHotelRoomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrHotelRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrHotelRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrHotelRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrHotelRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrHotelRoomInfo> selectByExample(SrHotelRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrHotelRoomInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrHotelRoomInfo record, @Param("example") SrHotelRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrHotelRoomInfo record, @Param("example") SrHotelRoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrHotelRoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_hotel_room_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrHotelRoomInfo record);
}