package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrPublishInfo;
import com.ctrip.asp.commom.dao.auto.model.SrPublishInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrPublishInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrPublishInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrPublishInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrPublishInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrPublishInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrPublishInfo> selectByExample(SrPublishInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrPublishInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrPublishInfo record, @Param("example") SrPublishInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrPublishInfo record, @Param("example") SrPublishInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrPublishInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publish_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrPublishInfo record);
}