package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrPublishroomRsLog;
import com.ctrip.asp.commom.dao.auto.model.SrPublishroomRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrPublishroomRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrPublishroomRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrPublishroomRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrPublishroomRsLog> selectByExampleWithBLOBs(SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrPublishroomRsLog> selectByExample(SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrPublishroomRsLog record, @Param("example") SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SrPublishroomRsLog record, @Param("example") SrPublishroomRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrPublishroomRsLog record, @Param("example") SrPublishroomRsLogExample example);
}