package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrPublishroomLog;
import com.ctrip.asp.commom.dao.auto.model.SrPublishroomLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrPublishroomLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrPublishroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrPublishroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrPublishroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrPublishroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrPublishroomLog> selectByExample(SrPublishroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrPublishroomLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrPublishroomLog record, @Param("example") SrPublishroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrPublishroomLog record, @Param("example") SrPublishroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrPublishroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_publishroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrPublishroomLog record);
}