package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrRoomstatusRsLog;
import com.ctrip.asp.commom.dao.auto.model.SrRoomstatusRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrRoomstatusRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrRoomstatusRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrRoomstatusRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrRoomstatusRsLog> selectByExampleWithBLOBs(SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrRoomstatusRsLog> selectByExample(SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrRoomstatusRsLog record, @Param("example") SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SrRoomstatusRsLog record, @Param("example") SrRoomstatusRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_roomstatus_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrRoomstatusRsLog record, @Param("example") SrRoomstatusRsLogExample example);
}