package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectresultLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectresultLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectresultLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectresultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectresultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectresultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectresultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectresultLog> selectByExample(SrSelectresultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrSelectresultLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectresultLog record, @Param("example") SrSelectresultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectresultLog record, @Param("example") SrSelectresultLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrSelectresultLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrSelectresultLog record);
}