package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectroomLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectroomLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectroomLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectroomLog> selectByExample(SrSelectroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrSelectroomLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectroomLog record, @Param("example") SrSelectroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectroomLog record, @Param("example") SrSelectroomLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrSelectroomLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrSelectroomLog record);
}