package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectroomInfo;
import com.ctrip.asp.commom.dao.auto.model.SrSelectroomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectroomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectroomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectroomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectroomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectroomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectroomInfo> selectByExample(SrSelectroomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrSelectroomInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectroomInfo record, @Param("example") SrSelectroomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectroomInfo record, @Param("example") SrSelectroomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrSelectroomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrSelectroomInfo record);
}