package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectorderLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectorderLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectorderLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectorderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectorderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectorderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectorderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectorderLog> selectByExample(SrSelectorderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    SrSelectorderLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectorderLog record, @Param("example") SrSelectorderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectorderLog record, @Param("example") SrSelectorderLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(SrSelectorderLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(SrSelectorderLog record);
}