package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectorderRsLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectorderRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectorderRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectorderRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectorderRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectorderRsLog> selectByExampleWithBLOBs(SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectorderRsLog> selectByExample(SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectorderRsLog record, @Param("example") SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SrSelectorderRsLog record, @Param("example") SrSelectorderRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectorder_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectorderRsLog record, @Param("example") SrSelectorderRsLogExample example);
}