package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectresultRsLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectresultRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectresultRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectresultRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectresultRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectresultRsLog> selectByExampleWithBLOBs(SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectresultRsLog> selectByExample(SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectresultRsLog record, @Param("example") SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SrSelectresultRsLog record, @Param("example") SrSelectresultRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectresult_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectresultRsLog record, @Param("example") SrSelectresultRsLogExample example);
}