package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.SrSelectroomRqLog;
import com.ctrip.asp.commom.dao.auto.model.SrSelectroomRqLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SrSelectroomRqLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(SrSelectroomRqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(SrSelectroomRqLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectroomRqLog> selectByExampleWithBLOBs(SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<SrSelectroomRqLog> selectByExample(SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SrSelectroomRqLog record, @Param("example") SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SrSelectroomRqLog record, @Param("example") SrSelectroomRqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sr_selectroom_rq_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") SrSelectroomRqLog record, @Param("example") SrSelectroomRqLogExample example);
}