package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcDevicecontrolLog;
import com.ctrip.asp.commom.dao.auto.model.UcDevicecontrolLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcDevicecontrolLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcDevicecontrolLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcDevicecontrolLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcDevicecontrolLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcDevicecontrolLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcDevicecontrolLog> selectByExample(UcDevicecontrolLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcDevicecontrolLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcDevicecontrolLog record, @Param("example") UcDevicecontrolLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcDevicecontrolLog record, @Param("example") UcDevicecontrolLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcDevicecontrolLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_devicecontrol_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcDevicecontrolLog record);
}