package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcDevicestatusLog;
import com.ctrip.asp.commom.dao.auto.model.UcDevicestatusLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcDevicestatusLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcDevicestatusLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcDevicestatusLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcDevicestatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcDevicestatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcDevicestatusLog> selectByExample(UcDevicestatusLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcDevicestatusLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcDevicestatusLog record, @Param("example") UcDevicestatusLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcDevicestatusLog record, @Param("example") UcDevicestatusLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcDevicestatusLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_deviceStatus_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcDevicestatusLog record);
}