package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcOrderGuestInfo;
import com.ctrip.asp.commom.dao.auto.model.UcOrderGuestInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcOrderGuestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcOrderGuestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcOrderGuestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcOrderGuestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcOrderGuestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcOrderGuestInfo> selectByExample(UcOrderGuestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcOrderGuestInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcOrderGuestInfo record, @Param("example") UcOrderGuestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcOrderGuestInfo record, @Param("example") UcOrderGuestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcOrderGuestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_guest_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcOrderGuestInfo record);
}