package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcOrderInfo;
import com.ctrip.asp.commom.dao.auto.model.UcOrderInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcOrderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcOrderInfo> selectByExample(UcOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcOrderInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcOrderInfo record, @Param("example") UcOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcOrderInfo record, @Param("example") UcOrderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcOrderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_order_info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcOrderInfo record);
}