package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcRoompowerLog;
import com.ctrip.asp.commom.dao.auto.model.UcRoompowerLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcRoompowerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcRoompowerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcRoompowerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcRoompowerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcRoompowerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcRoompowerLog> selectByExample(UcRoompowerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcRoompowerLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcRoompowerLog record, @Param("example") UcRoompowerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcRoompowerLog record, @Param("example") UcRoompowerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcRoompowerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roompower_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcRoompowerLog record);
}