package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcRoomalertStatistics;
import com.ctrip.asp.commom.dao.auto.model.UcRoomalertStatisticsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcRoomalertStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcRoomalertStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcRoomalertStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcRoomalertStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcRoomalertStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcRoomalertStatistics> selectByExample(UcRoomalertStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcRoomalertStatistics selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcRoomalertStatistics record, @Param("example") UcRoomalertStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcRoomalertStatistics record, @Param("example") UcRoomalertStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcRoomalertStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_statistics
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcRoomalertStatistics record);
}