package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcRoomalertLog;
import com.ctrip.asp.commom.dao.auto.model.UcRoomalertLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcRoomalertLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcRoomalertLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcRoomalertLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcRoomalertLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcRoomalertLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcRoomalertLog> selectByExample(UcRoomalertLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcRoomalertLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcRoomalertLog record, @Param("example") UcRoomalertLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcRoomalertLog record, @Param("example") UcRoomalertLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcRoomalertLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_roomalert_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcRoomalertLog record);
}