package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcUserauthLog;
import com.ctrip.asp.commom.dao.auto.model.UcUserauthLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcUserauthLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcUserauthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcUserauthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcUserauthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcUserauthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcUserauthLog> selectByExample(UcUserauthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    UcUserauthLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcUserauthLog record, @Param("example") UcUserauthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcUserauthLog record, @Param("example") UcUserauthLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKeySelective(UcUserauthLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByPrimaryKey(UcUserauthLog record);
}