package com.ctrip.asp.commom.dao.auto.client;

import com.ctrip.asp.commom.dao.auto.model.UcUserauthRsLog;
import com.ctrip.asp.commom.dao.auto.model.UcUserauthRsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcUserauthRsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int countByExample(UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int deleteByExample(UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insert(UcUserauthRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int insertSelective(UcUserauthRsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcUserauthRsLog> selectByExampleWithBLOBs(UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    List<UcUserauthRsLog> selectByExample(UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") UcUserauthRsLog record, @Param("example") UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") UcUserauthRsLog record, @Param("example") UcUserauthRsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_userauth_rs_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    int updateByExample(@Param("record") UcUserauthRsLog record, @Param("example") UcUserauthRsLogExample example);
}