package com.ctrip.asp.commom.dao.auto.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AspCtripMappingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public AspCtripMappingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNull() {
            addCriterion("channel_code is null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIsNotNull() {
            addCriterion("channel_code is not null");
            return (Criteria) this;
        }

        public Criteria andChannelCodeEqualTo(String value) {
            addCriterion("channel_code =", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotEqualTo(String value) {
            addCriterion("channel_code <>", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThan(String value) {
            addCriterion("channel_code >", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("channel_code >=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThan(String value) {
            addCriterion("channel_code <", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLessThanOrEqualTo(String value) {
            addCriterion("channel_code <=", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeLike(String value) {
            addCriterion("channel_code like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotLike(String value) {
            addCriterion("channel_code not like", value, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeIn(List<String> values) {
            addCriterion("channel_code in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotIn(List<String> values) {
            addCriterion("channel_code not in", values, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeBetween(String value1, String value2) {
            addCriterion("channel_code between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andChannelCodeNotBetween(String value1, String value2) {
            addCriterion("channel_code not between", value1, value2, "channelCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNull() {
            addCriterion("pms_code is null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNotNull() {
            addCriterion("pms_code is not null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeEqualTo(String value) {
            addCriterion("pms_code =", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotEqualTo(String value) {
            addCriterion("pms_code <>", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThan(String value) {
            addCriterion("pms_code >", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("pms_code >=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThan(String value) {
            addCriterion("pms_code <", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThanOrEqualTo(String value) {
            addCriterion("pms_code <=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLike(String value) {
            addCriterion("pms_code like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotLike(String value) {
            addCriterion("pms_code not like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIn(List<String> values) {
            addCriterion("pms_code in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotIn(List<String> values) {
            addCriterion("pms_code not in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeBetween(String value1, String value2) {
            addCriterion("pms_code between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotBetween(String value1, String value2) {
            addCriterion("pms_code not between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNull() {
            addCriterion("hotel_code is null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNotNull() {
            addCriterion("hotel_code is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeEqualTo(String value) {
            addCriterion("hotel_code =", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotEqualTo(String value) {
            addCriterion("hotel_code <>", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThan(String value) {
            addCriterion("hotel_code >", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_code >=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThan(String value) {
            addCriterion("hotel_code <", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThanOrEqualTo(String value) {
            addCriterion("hotel_code <=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLike(String value) {
            addCriterion("hotel_code like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotLike(String value) {
            addCriterion("hotel_code not like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIn(List<String> values) {
            addCriterion("hotel_code in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotIn(List<String> values) {
            addCriterion("hotel_code not in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeBetween(String value1, String value2) {
            addCriterion("hotel_code between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotBetween(String value1, String value2) {
            addCriterion("hotel_code not between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeIsNull() {
            addCriterion("room_type_code is null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeIsNotNull() {
            addCriterion("room_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeEqualTo(String value) {
            addCriterion("room_type_code =", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeNotEqualTo(String value) {
            addCriterion("room_type_code <>", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeGreaterThan(String value) {
            addCriterion("room_type_code >", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("room_type_code >=", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeLessThan(String value) {
            addCriterion("room_type_code <", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("room_type_code <=", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeLike(String value) {
            addCriterion("room_type_code like", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeNotLike(String value) {
            addCriterion("room_type_code not like", value, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeIn(List<String> values) {
            addCriterion("room_type_code in", values, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeNotIn(List<String> values) {
            addCriterion("room_type_code not in", values, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeBetween(String value1, String value2) {
            addCriterion("room_type_code between", value1, value2, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeCodeNotBetween(String value1, String value2) {
            addCriterion("room_type_code not between", value1, value2, "roomTypeCode");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameIsNull() {
            addCriterion("room_type_name is null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameIsNotNull() {
            addCriterion("room_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameEqualTo(String value) {
            addCriterion("room_type_name =", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameNotEqualTo(String value) {
            addCriterion("room_type_name <>", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameGreaterThan(String value) {
            addCriterion("room_type_name >", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("room_type_name >=", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameLessThan(String value) {
            addCriterion("room_type_name <", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameLessThanOrEqualTo(String value) {
            addCriterion("room_type_name <=", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameLike(String value) {
            addCriterion("room_type_name like", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameNotLike(String value) {
            addCriterion("room_type_name not like", value, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameIn(List<String> values) {
            addCriterion("room_type_name in", values, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameNotIn(List<String> values) {
            addCriterion("room_type_name not in", values, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameBetween(String value1, String value2) {
            addCriterion("room_type_name between", value1, value2, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRoomTypeNameNotBetween(String value1, String value2) {
            addCriterion("room_type_name not between", value1, value2, "roomTypeName");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeIsNull() {
            addCriterion("rate_plan_code is null");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeIsNotNull() {
            addCriterion("rate_plan_code is not null");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeEqualTo(String value) {
            addCriterion("rate_plan_code =", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeNotEqualTo(String value) {
            addCriterion("rate_plan_code <>", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeGreaterThan(String value) {
            addCriterion("rate_plan_code >", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeGreaterThanOrEqualTo(String value) {
            addCriterion("rate_plan_code >=", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeLessThan(String value) {
            addCriterion("rate_plan_code <", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeLessThanOrEqualTo(String value) {
            addCriterion("rate_plan_code <=", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeLike(String value) {
            addCriterion("rate_plan_code like", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeNotLike(String value) {
            addCriterion("rate_plan_code not like", value, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeIn(List<String> values) {
            addCriterion("rate_plan_code in", values, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeNotIn(List<String> values) {
            addCriterion("rate_plan_code not in", values, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeBetween(String value1, String value2) {
            addCriterion("rate_plan_code between", value1, value2, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanCodeNotBetween(String value1, String value2) {
            addCriterion("rate_plan_code not between", value1, value2, "ratePlanCode");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameIsNull() {
            addCriterion("rate_plan_name is null");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameIsNotNull() {
            addCriterion("rate_plan_name is not null");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameEqualTo(String value) {
            addCriterion("rate_plan_name =", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameNotEqualTo(String value) {
            addCriterion("rate_plan_name <>", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameGreaterThan(String value) {
            addCriterion("rate_plan_name >", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameGreaterThanOrEqualTo(String value) {
            addCriterion("rate_plan_name >=", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameLessThan(String value) {
            addCriterion("rate_plan_name <", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameLessThanOrEqualTo(String value) {
            addCriterion("rate_plan_name <=", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameLike(String value) {
            addCriterion("rate_plan_name like", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameNotLike(String value) {
            addCriterion("rate_plan_name not like", value, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameIn(List<String> values) {
            addCriterion("rate_plan_name in", values, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameNotIn(List<String> values) {
            addCriterion("rate_plan_name not in", values, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameBetween(String value1, String value2) {
            addCriterion("rate_plan_name between", value1, value2, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andRatePlanNameNotBetween(String value1, String value2) {
            addCriterion("rate_plan_name not between", value1, value2, "ratePlanName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeIsNull() {
            addCriterion("balance_type_code is null");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeIsNotNull() {
            addCriterion("balance_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeEqualTo(String value) {
            addCriterion("balance_type_code =", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeNotEqualTo(String value) {
            addCriterion("balance_type_code <>", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeGreaterThan(String value) {
            addCriterion("balance_type_code >", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("balance_type_code >=", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeLessThan(String value) {
            addCriterion("balance_type_code <", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("balance_type_code <=", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeLike(String value) {
            addCriterion("balance_type_code like", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeNotLike(String value) {
            addCriterion("balance_type_code not like", value, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeIn(List<String> values) {
            addCriterion("balance_type_code in", values, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeNotIn(List<String> values) {
            addCriterion("balance_type_code not in", values, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeBetween(String value1, String value2) {
            addCriterion("balance_type_code between", value1, value2, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeCodeNotBetween(String value1, String value2) {
            addCriterion("balance_type_code not between", value1, value2, "balanceTypeCode");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameIsNull() {
            addCriterion("balance_type_name is null");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameIsNotNull() {
            addCriterion("balance_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameEqualTo(String value) {
            addCriterion("balance_type_name =", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameNotEqualTo(String value) {
            addCriterion("balance_type_name <>", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameGreaterThan(String value) {
            addCriterion("balance_type_name >", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("balance_type_name >=", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameLessThan(String value) {
            addCriterion("balance_type_name <", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameLessThanOrEqualTo(String value) {
            addCriterion("balance_type_name <=", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameLike(String value) {
            addCriterion("balance_type_name like", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameNotLike(String value) {
            addCriterion("balance_type_name not like", value, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameIn(List<String> values) {
            addCriterion("balance_type_name in", values, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameNotIn(List<String> values) {
            addCriterion("balance_type_name not in", values, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameBetween(String value1, String value2) {
            addCriterion("balance_type_name between", value1, value2, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andBalanceTypeNameNotBetween(String value1, String value2) {
            addCriterion("balance_type_name not between", value1, value2, "balanceTypeName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdIsNull() {
            addCriterion("channel_hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdIsNotNull() {
            addCriterion("channel_hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdEqualTo(String value) {
            addCriterion("channel_hotel_id =", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdNotEqualTo(String value) {
            addCriterion("channel_hotel_id <>", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdGreaterThan(String value) {
            addCriterion("channel_hotel_id >", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("channel_hotel_id >=", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdLessThan(String value) {
            addCriterion("channel_hotel_id <", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdLessThanOrEqualTo(String value) {
            addCriterion("channel_hotel_id <=", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdLike(String value) {
            addCriterion("channel_hotel_id like", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdNotLike(String value) {
            addCriterion("channel_hotel_id not like", value, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdIn(List<String> values) {
            addCriterion("channel_hotel_id in", values, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdNotIn(List<String> values) {
            addCriterion("channel_hotel_id not in", values, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdBetween(String value1, String value2) {
            addCriterion("channel_hotel_id between", value1, value2, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelIdNotBetween(String value1, String value2) {
            addCriterion("channel_hotel_id not between", value1, value2, "channelHotelId");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameIsNull() {
            addCriterion("channel_hotel_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameIsNotNull() {
            addCriterion("channel_hotel_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameEqualTo(String value) {
            addCriterion("channel_hotel_name =", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameNotEqualTo(String value) {
            addCriterion("channel_hotel_name <>", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameGreaterThan(String value) {
            addCriterion("channel_hotel_name >", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_hotel_name >=", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameLessThan(String value) {
            addCriterion("channel_hotel_name <", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameLessThanOrEqualTo(String value) {
            addCriterion("channel_hotel_name <=", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameLike(String value) {
            addCriterion("channel_hotel_name like", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameNotLike(String value) {
            addCriterion("channel_hotel_name not like", value, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameIn(List<String> values) {
            addCriterion("channel_hotel_name in", values, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameNotIn(List<String> values) {
            addCriterion("channel_hotel_name not in", values, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameBetween(String value1, String value2) {
            addCriterion("channel_hotel_name between", value1, value2, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelHotelNameNotBetween(String value1, String value2) {
            addCriterion("channel_hotel_name not between", value1, value2, "channelHotelName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdIsNull() {
            addCriterion("channel_room_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdIsNotNull() {
            addCriterion("channel_room_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdEqualTo(String value) {
            addCriterion("channel_room_id =", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdNotEqualTo(String value) {
            addCriterion("channel_room_id <>", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdGreaterThan(String value) {
            addCriterion("channel_room_id >", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdGreaterThanOrEqualTo(String value) {
            addCriterion("channel_room_id >=", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdLessThan(String value) {
            addCriterion("channel_room_id <", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdLessThanOrEqualTo(String value) {
            addCriterion("channel_room_id <=", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdLike(String value) {
            addCriterion("channel_room_id like", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdNotLike(String value) {
            addCriterion("channel_room_id not like", value, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdIn(List<String> values) {
            addCriterion("channel_room_id in", values, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdNotIn(List<String> values) {
            addCriterion("channel_room_id not in", values, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdBetween(String value1, String value2) {
            addCriterion("channel_room_id between", value1, value2, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomIdNotBetween(String value1, String value2) {
            addCriterion("channel_room_id not between", value1, value2, "channelRoomId");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameIsNull() {
            addCriterion("channel_room_name is null");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameIsNotNull() {
            addCriterion("channel_room_name is not null");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameEqualTo(String value) {
            addCriterion("channel_room_name =", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameNotEqualTo(String value) {
            addCriterion("channel_room_name <>", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameGreaterThan(String value) {
            addCriterion("channel_room_name >", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameGreaterThanOrEqualTo(String value) {
            addCriterion("channel_room_name >=", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameLessThan(String value) {
            addCriterion("channel_room_name <", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameLessThanOrEqualTo(String value) {
            addCriterion("channel_room_name <=", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameLike(String value) {
            addCriterion("channel_room_name like", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameNotLike(String value) {
            addCriterion("channel_room_name not like", value, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameIn(List<String> values) {
            addCriterion("channel_room_name in", values, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameNotIn(List<String> values) {
            addCriterion("channel_room_name not in", values, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameBetween(String value1, String value2) {
            addCriterion("channel_room_name between", value1, value2, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andChannelRoomNameNotBetween(String value1, String value2) {
            addCriterion("channel_room_name not between", value1, value2, "channelRoomName");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNull() {
            addCriterion("insert_time is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNotNull() {
            addCriterion("insert_time is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeEqualTo(Date value) {
            addCriterion("insert_time =", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotEqualTo(Date value) {
            addCriterion("insert_time <>", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThan(Date value) {
            addCriterion("insert_time >", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_time >=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThan(Date value) {
            addCriterion("insert_time <", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
            addCriterion("insert_time <=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIn(List<Date> values) {
            addCriterion("insert_time in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotIn(List<Date> values) {
            addCriterion("insert_time not in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeBetween(Date value1, Date value2) {
            addCriterion("insert_time between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
            addCriterion("insert_time not between", value1, value2, "insertTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_ctrip_mapping
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}