package com.ctrip.asp.commom.dao.auto.model;

import java.util.Date;

public class AspCtripMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.channel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.pms_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.hotel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.room_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.room_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.rate_plan_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String ratePlanCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.rate_plan_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String ratePlanName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.balance_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String balanceTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.balance_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String balanceTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.channel_hotel_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelHotelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.channel_hotel_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelHotelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.channel_room_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelRoomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.channel_room_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelRoomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_ctrip_mapping.insert_time
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.id
     *
     * @return the value of asp_ctrip_mapping.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.id
     *
     * @param id the value for asp_ctrip_mapping.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.channel_code
     *
     * @return the value of asp_ctrip_mapping.channel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.channel_code
     *
     * @param channelCode the value for asp_ctrip_mapping.channel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.pms_code
     *
     * @return the value of asp_ctrip_mapping.pms_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.pms_code
     *
     * @param pmsCode the value for asp_ctrip_mapping.pms_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.hotel_code
     *
     * @return the value of asp_ctrip_mapping.hotel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.hotel_code
     *
     * @param hotelCode the value for asp_ctrip_mapping.hotel_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.room_type_code
     *
     * @return the value of asp_ctrip_mapping.room_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.room_type_code
     *
     * @param roomTypeCode the value for asp_ctrip_mapping.room_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.room_type_name
     *
     * @return the value of asp_ctrip_mapping.room_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomTypeName() {
        return roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.room_type_name
     *
     * @param roomTypeName the value for asp_ctrip_mapping.room_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomTypeName(String roomTypeName) {
        this.roomTypeName = roomTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.rate_plan_code
     *
     * @return the value of asp_ctrip_mapping.rate_plan_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRatePlanCode() {
        return ratePlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.rate_plan_code
     *
     * @param ratePlanCode the value for asp_ctrip_mapping.rate_plan_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRatePlanCode(String ratePlanCode) {
        this.ratePlanCode = ratePlanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.rate_plan_name
     *
     * @return the value of asp_ctrip_mapping.rate_plan_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRatePlanName() {
        return ratePlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.rate_plan_name
     *
     * @param ratePlanName the value for asp_ctrip_mapping.rate_plan_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRatePlanName(String ratePlanName) {
        this.ratePlanName = ratePlanName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.balance_type_code
     *
     * @return the value of asp_ctrip_mapping.balance_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBalanceTypeCode() {
        return balanceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.balance_type_code
     *
     * @param balanceTypeCode the value for asp_ctrip_mapping.balance_type_code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBalanceTypeCode(String balanceTypeCode) {
        this.balanceTypeCode = balanceTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.balance_type_name
     *
     * @return the value of asp_ctrip_mapping.balance_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBalanceTypeName() {
        return balanceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.balance_type_name
     *
     * @param balanceTypeName the value for asp_ctrip_mapping.balance_type_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBalanceTypeName(String balanceTypeName) {
        this.balanceTypeName = balanceTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.channel_hotel_id
     *
     * @return the value of asp_ctrip_mapping.channel_hotel_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelHotelId() {
        return channelHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.channel_hotel_id
     *
     * @param channelHotelId the value for asp_ctrip_mapping.channel_hotel_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelHotelId(String channelHotelId) {
        this.channelHotelId = channelHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.channel_hotel_name
     *
     * @return the value of asp_ctrip_mapping.channel_hotel_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelHotelName() {
        return channelHotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.channel_hotel_name
     *
     * @param channelHotelName the value for asp_ctrip_mapping.channel_hotel_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelHotelName(String channelHotelName) {
        this.channelHotelName = channelHotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.channel_room_id
     *
     * @return the value of asp_ctrip_mapping.channel_room_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelRoomId() {
        return channelRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.channel_room_id
     *
     * @param channelRoomId the value for asp_ctrip_mapping.channel_room_id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelRoomId(String channelRoomId) {
        this.channelRoomId = channelRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.channel_room_name
     *
     * @return the value of asp_ctrip_mapping.channel_room_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelRoomName() {
        return channelRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.channel_room_name
     *
     * @param channelRoomName the value for asp_ctrip_mapping.channel_room_name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelRoomName(String channelRoomName) {
        this.channelRoomName = channelRoomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_ctrip_mapping.insert_time
     *
     * @return the value of asp_ctrip_mapping.insert_time
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_ctrip_mapping.insert_time
     *
     * @param insertTime the value for asp_ctrip_mapping.insert_time
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}