package com.ctrip.asp.commom.dao.auto.model;

public class AspHotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Pms_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Brand
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Is_SelectRoom
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer isSelectroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Is_UserControl
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer isUsercontrol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Is_AutoService
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer isAutoservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Contact
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Tel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Hotel_Address
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Offline_Cause
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String offlineCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Description
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_hotel.Active_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer activeStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.ID
     *
     * @return the value of asp_hotel.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.ID
     *
     * @param id the value for asp_hotel.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Code
     *
     * @return the value of asp_hotel.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Code
     *
     * @param hotelCode the value for asp_hotel.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Name
     *
     * @return the value of asp_hotel.Hotel_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Name
     *
     * @param hotelName the value for asp_hotel.Hotel_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Pms_Code
     *
     * @return the value of asp_hotel.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Pms_Code
     *
     * @param pmsCode the value for asp_hotel.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Pms_Name
     *
     * @return the value of asp_hotel.Pms_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsName() {
        return pmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Pms_Name
     *
     * @param pmsName the value for asp_hotel.Pms_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsName(String pmsName) {
        this.pmsName = pmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Brand
     *
     * @return the value of asp_hotel.Brand
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Brand
     *
     * @param brand the value for asp_hotel.Brand
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Is_SelectRoom
     *
     * @return the value of asp_hotel.Is_SelectRoom
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIsSelectroom() {
        return isSelectroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Is_SelectRoom
     *
     * @param isSelectroom the value for asp_hotel.Is_SelectRoom
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIsSelectroom(Integer isSelectroom) {
        this.isSelectroom = isSelectroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Is_UserControl
     *
     * @return the value of asp_hotel.Is_UserControl
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIsUsercontrol() {
        return isUsercontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Is_UserControl
     *
     * @param isUsercontrol the value for asp_hotel.Is_UserControl
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIsUsercontrol(Integer isUsercontrol) {
        this.isUsercontrol = isUsercontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Is_AutoService
     *
     * @return the value of asp_hotel.Is_AutoService
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIsAutoservice() {
        return isAutoservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Is_AutoService
     *
     * @param isAutoservice the value for asp_hotel.Is_AutoService
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIsAutoservice(Integer isAutoservice) {
        this.isAutoservice = isAutoservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Contact
     *
     * @return the value of asp_hotel.Hotel_Contact
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelContact() {
        return hotelContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Contact
     *
     * @param hotelContact the value for asp_hotel.Hotel_Contact
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelContact(String hotelContact) {
        this.hotelContact = hotelContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Tel
     *
     * @return the value of asp_hotel.Hotel_Tel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelTel() {
        return hotelTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Tel
     *
     * @param hotelTel the value for asp_hotel.Hotel_Tel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelTel(String hotelTel) {
        this.hotelTel = hotelTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Email
     *
     * @return the value of asp_hotel.Hotel_Email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelEmail() {
        return hotelEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Email
     *
     * @param hotelEmail the value for asp_hotel.Hotel_Email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelEmail(String hotelEmail) {
        this.hotelEmail = hotelEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Hotel_Address
     *
     * @return the value of asp_hotel.Hotel_Address
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelAddress() {
        return hotelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Hotel_Address
     *
     * @param hotelAddress the value for asp_hotel.Hotel_Address
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Offline_Cause
     *
     * @return the value of asp_hotel.Offline_Cause
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOfflineCause() {
        return offlineCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Offline_Cause
     *
     * @param offlineCause the value for asp_hotel.Offline_Cause
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOfflineCause(String offlineCause) {
        this.offlineCause = offlineCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Description
     *
     * @return the value of asp_hotel.Description
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Description
     *
     * @param description the value for asp_hotel.Description
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Create_DateTime
     *
     * @return the value of asp_hotel.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Create_DateTime
     *
     * @param createDatetime the value for asp_hotel.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Long createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Update_DateTime
     *
     * @return the value of asp_hotel.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Update_DateTime
     *
     * @param updateDatetime the value for asp_hotel.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdateDatetime(Long updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Record_Status
     *
     * @return the value of asp_hotel.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Record_Status
     *
     * @param recordStatus the value for asp_hotel.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_hotel.Active_Status
     *
     * @return the value of asp_hotel.Active_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getActiveStatus() {
        return activeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_hotel.Active_Status
     *
     * @param activeStatus the value for asp_hotel.Active_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setActiveStatus(Integer activeStatus) {
        this.activeStatus = activeStatus;
    }
}