package com.ctrip.asp.commom.dao.auto.model;

import java.util.ArrayList;
import java.util.List;

public class AspHotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public AspHotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNull() {
            addCriterion("Hotel_Code is null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNotNull() {
            addCriterion("Hotel_Code is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeEqualTo(String value) {
            addCriterion("Hotel_Code =", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotEqualTo(String value) {
            addCriterion("Hotel_Code <>", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThan(String value) {
            addCriterion("Hotel_Code >", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Code >=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThan(String value) {
            addCriterion("Hotel_Code <", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Code <=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLike(String value) {
            addCriterion("Hotel_Code like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotLike(String value) {
            addCriterion("Hotel_Code not like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIn(List<String> values) {
            addCriterion("Hotel_Code in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotIn(List<String> values) {
            addCriterion("Hotel_Code not in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeBetween(String value1, String value2) {
            addCriterion("Hotel_Code between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotBetween(String value1, String value2) {
            addCriterion("Hotel_Code not between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("Hotel_Name is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("Hotel_Name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("Hotel_Name =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("Hotel_Name <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("Hotel_Name >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Name >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("Hotel_Name <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Name <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("Hotel_Name like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("Hotel_Name not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("Hotel_Name in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("Hotel_Name not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("Hotel_Name between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("Hotel_Name not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNull() {
            addCriterion("Pms_Code is null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNotNull() {
            addCriterion("Pms_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeEqualTo(String value) {
            addCriterion("Pms_Code =", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotEqualTo(String value) {
            addCriterion("Pms_Code <>", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThan(String value) {
            addCriterion("Pms_Code >", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Pms_Code >=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThan(String value) {
            addCriterion("Pms_Code <", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThanOrEqualTo(String value) {
            addCriterion("Pms_Code <=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLike(String value) {
            addCriterion("Pms_Code like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotLike(String value) {
            addCriterion("Pms_Code not like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIn(List<String> values) {
            addCriterion("Pms_Code in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotIn(List<String> values) {
            addCriterion("Pms_Code not in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeBetween(String value1, String value2) {
            addCriterion("Pms_Code between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotBetween(String value1, String value2) {
            addCriterion("Pms_Code not between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsNameIsNull() {
            addCriterion("Pms_Name is null");
            return (Criteria) this;
        }

        public Criteria andPmsNameIsNotNull() {
            addCriterion("Pms_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPmsNameEqualTo(String value) {
            addCriterion("Pms_Name =", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotEqualTo(String value) {
            addCriterion("Pms_Name <>", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameGreaterThan(String value) {
            addCriterion("Pms_Name >", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameGreaterThanOrEqualTo(String value) {
            addCriterion("Pms_Name >=", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLessThan(String value) {
            addCriterion("Pms_Name <", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLessThanOrEqualTo(String value) {
            addCriterion("Pms_Name <=", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameLike(String value) {
            addCriterion("Pms_Name like", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotLike(String value) {
            addCriterion("Pms_Name not like", value, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameIn(List<String> values) {
            addCriterion("Pms_Name in", values, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotIn(List<String> values) {
            addCriterion("Pms_Name not in", values, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameBetween(String value1, String value2) {
            addCriterion("Pms_Name between", value1, value2, "pmsName");
            return (Criteria) this;
        }

        public Criteria andPmsNameNotBetween(String value1, String value2) {
            addCriterion("Pms_Name not between", value1, value2, "pmsName");
            return (Criteria) this;
        }

        public Criteria andBrandIsNull() {
            addCriterion("Brand is null");
            return (Criteria) this;
        }

        public Criteria andBrandIsNotNull() {
            addCriterion("Brand is not null");
            return (Criteria) this;
        }

        public Criteria andBrandEqualTo(String value) {
            addCriterion("Brand =", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotEqualTo(String value) {
            addCriterion("Brand <>", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThan(String value) {
            addCriterion("Brand >", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandGreaterThanOrEqualTo(String value) {
            addCriterion("Brand >=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThan(String value) {
            addCriterion("Brand <", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLessThanOrEqualTo(String value) {
            addCriterion("Brand <=", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandLike(String value) {
            addCriterion("Brand like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotLike(String value) {
            addCriterion("Brand not like", value, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandIn(List<String> values) {
            addCriterion("Brand in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotIn(List<String> values) {
            addCriterion("Brand not in", values, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandBetween(String value1, String value2) {
            addCriterion("Brand between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andBrandNotBetween(String value1, String value2) {
            addCriterion("Brand not between", value1, value2, "brand");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomIsNull() {
            addCriterion("Is_SelectRoom is null");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomIsNotNull() {
            addCriterion("Is_SelectRoom is not null");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomEqualTo(Integer value) {
            addCriterion("Is_SelectRoom =", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomNotEqualTo(Integer value) {
            addCriterion("Is_SelectRoom <>", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomGreaterThan(Integer value) {
            addCriterion("Is_SelectRoom >", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomGreaterThanOrEqualTo(Integer value) {
            addCriterion("Is_SelectRoom >=", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomLessThan(Integer value) {
            addCriterion("Is_SelectRoom <", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomLessThanOrEqualTo(Integer value) {
            addCriterion("Is_SelectRoom <=", value, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomIn(List<Integer> values) {
            addCriterion("Is_SelectRoom in", values, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomNotIn(List<Integer> values) {
            addCriterion("Is_SelectRoom not in", values, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomBetween(Integer value1, Integer value2) {
            addCriterion("Is_SelectRoom between", value1, value2, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsSelectroomNotBetween(Integer value1, Integer value2) {
            addCriterion("Is_SelectRoom not between", value1, value2, "isSelectroom");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolIsNull() {
            addCriterion("Is_UserControl is null");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolIsNotNull() {
            addCriterion("Is_UserControl is not null");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolEqualTo(Integer value) {
            addCriterion("Is_UserControl =", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolNotEqualTo(Integer value) {
            addCriterion("Is_UserControl <>", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolGreaterThan(Integer value) {
            addCriterion("Is_UserControl >", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolGreaterThanOrEqualTo(Integer value) {
            addCriterion("Is_UserControl >=", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolLessThan(Integer value) {
            addCriterion("Is_UserControl <", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolLessThanOrEqualTo(Integer value) {
            addCriterion("Is_UserControl <=", value, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolIn(List<Integer> values) {
            addCriterion("Is_UserControl in", values, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolNotIn(List<Integer> values) {
            addCriterion("Is_UserControl not in", values, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolBetween(Integer value1, Integer value2) {
            addCriterion("Is_UserControl between", value1, value2, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsUsercontrolNotBetween(Integer value1, Integer value2) {
            addCriterion("Is_UserControl not between", value1, value2, "isUsercontrol");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceIsNull() {
            addCriterion("Is_AutoService is null");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceIsNotNull() {
            addCriterion("Is_AutoService is not null");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceEqualTo(Integer value) {
            addCriterion("Is_AutoService =", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceNotEqualTo(Integer value) {
            addCriterion("Is_AutoService <>", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceGreaterThan(Integer value) {
            addCriterion("Is_AutoService >", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceGreaterThanOrEqualTo(Integer value) {
            addCriterion("Is_AutoService >=", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceLessThan(Integer value) {
            addCriterion("Is_AutoService <", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceLessThanOrEqualTo(Integer value) {
            addCriterion("Is_AutoService <=", value, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceIn(List<Integer> values) {
            addCriterion("Is_AutoService in", values, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceNotIn(List<Integer> values) {
            addCriterion("Is_AutoService not in", values, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceBetween(Integer value1, Integer value2) {
            addCriterion("Is_AutoService between", value1, value2, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andIsAutoserviceNotBetween(Integer value1, Integer value2) {
            addCriterion("Is_AutoService not between", value1, value2, "isAutoservice");
            return (Criteria) this;
        }

        public Criteria andHotelContactIsNull() {
            addCriterion("Hotel_Contact is null");
            return (Criteria) this;
        }

        public Criteria andHotelContactIsNotNull() {
            addCriterion("Hotel_Contact is not null");
            return (Criteria) this;
        }

        public Criteria andHotelContactEqualTo(String value) {
            addCriterion("Hotel_Contact =", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotEqualTo(String value) {
            addCriterion("Hotel_Contact <>", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactGreaterThan(String value) {
            addCriterion("Hotel_Contact >", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Contact >=", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLessThan(String value) {
            addCriterion("Hotel_Contact <", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Contact <=", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactLike(String value) {
            addCriterion("Hotel_Contact like", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotLike(String value) {
            addCriterion("Hotel_Contact not like", value, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactIn(List<String> values) {
            addCriterion("Hotel_Contact in", values, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotIn(List<String> values) {
            addCriterion("Hotel_Contact not in", values, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactBetween(String value1, String value2) {
            addCriterion("Hotel_Contact between", value1, value2, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelContactNotBetween(String value1, String value2) {
            addCriterion("Hotel_Contact not between", value1, value2, "hotelContact");
            return (Criteria) this;
        }

        public Criteria andHotelTelIsNull() {
            addCriterion("Hotel_Tel is null");
            return (Criteria) this;
        }

        public Criteria andHotelTelIsNotNull() {
            addCriterion("Hotel_Tel is not null");
            return (Criteria) this;
        }

        public Criteria andHotelTelEqualTo(String value) {
            addCriterion("Hotel_Tel =", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelNotEqualTo(String value) {
            addCriterion("Hotel_Tel <>", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelGreaterThan(String value) {
            addCriterion("Hotel_Tel >", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Tel >=", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelLessThan(String value) {
            addCriterion("Hotel_Tel <", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Tel <=", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelLike(String value) {
            addCriterion("Hotel_Tel like", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelNotLike(String value) {
            addCriterion("Hotel_Tel not like", value, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelIn(List<String> values) {
            addCriterion("Hotel_Tel in", values, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelNotIn(List<String> values) {
            addCriterion("Hotel_Tel not in", values, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelBetween(String value1, String value2) {
            addCriterion("Hotel_Tel between", value1, value2, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelTelNotBetween(String value1, String value2) {
            addCriterion("Hotel_Tel not between", value1, value2, "hotelTel");
            return (Criteria) this;
        }

        public Criteria andHotelEmailIsNull() {
            addCriterion("Hotel_Email is null");
            return (Criteria) this;
        }

        public Criteria andHotelEmailIsNotNull() {
            addCriterion("Hotel_Email is not null");
            return (Criteria) this;
        }

        public Criteria andHotelEmailEqualTo(String value) {
            addCriterion("Hotel_Email =", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailNotEqualTo(String value) {
            addCriterion("Hotel_Email <>", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailGreaterThan(String value) {
            addCriterion("Hotel_Email >", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Email >=", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailLessThan(String value) {
            addCriterion("Hotel_Email <", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Email <=", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailLike(String value) {
            addCriterion("Hotel_Email like", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailNotLike(String value) {
            addCriterion("Hotel_Email not like", value, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailIn(List<String> values) {
            addCriterion("Hotel_Email in", values, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailNotIn(List<String> values) {
            addCriterion("Hotel_Email not in", values, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailBetween(String value1, String value2) {
            addCriterion("Hotel_Email between", value1, value2, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelEmailNotBetween(String value1, String value2) {
            addCriterion("Hotel_Email not between", value1, value2, "hotelEmail");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNull() {
            addCriterion("Hotel_Address is null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNotNull() {
            addCriterion("Hotel_Address is not null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressEqualTo(String value) {
            addCriterion("Hotel_Address =", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotEqualTo(String value) {
            addCriterion("Hotel_Address <>", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThan(String value) {
            addCriterion("Hotel_Address >", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Address >=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThan(String value) {
            addCriterion("Hotel_Address <", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Address <=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLike(String value) {
            addCriterion("Hotel_Address like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotLike(String value) {
            addCriterion("Hotel_Address not like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIn(List<String> values) {
            addCriterion("Hotel_Address in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotIn(List<String> values) {
            addCriterion("Hotel_Address not in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressBetween(String value1, String value2) {
            addCriterion("Hotel_Address between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotBetween(String value1, String value2) {
            addCriterion("Hotel_Address not between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseIsNull() {
            addCriterion("Offline_Cause is null");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseIsNotNull() {
            addCriterion("Offline_Cause is not null");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseEqualTo(String value) {
            addCriterion("Offline_Cause =", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseNotEqualTo(String value) {
            addCriterion("Offline_Cause <>", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseGreaterThan(String value) {
            addCriterion("Offline_Cause >", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseGreaterThanOrEqualTo(String value) {
            addCriterion("Offline_Cause >=", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseLessThan(String value) {
            addCriterion("Offline_Cause <", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseLessThanOrEqualTo(String value) {
            addCriterion("Offline_Cause <=", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseLike(String value) {
            addCriterion("Offline_Cause like", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseNotLike(String value) {
            addCriterion("Offline_Cause not like", value, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseIn(List<String> values) {
            addCriterion("Offline_Cause in", values, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseNotIn(List<String> values) {
            addCriterion("Offline_Cause not in", values, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseBetween(String value1, String value2) {
            addCriterion("Offline_Cause between", value1, value2, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andOfflineCauseNotBetween(String value1, String value2) {
            addCriterion("Offline_Cause not between", value1, value2, "offlineCause");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("Create_DateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("Create_DateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(Long value) {
            addCriterion("Create_DateTime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Long value) {
            addCriterion("Create_DateTime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(Long value) {
            addCriterion("Create_DateTime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("Create_DateTime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(Long value) {
            addCriterion("Create_DateTime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Long value) {
            addCriterion("Create_DateTime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<Long> values) {
            addCriterion("Create_DateTime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<Long> values) {
            addCriterion("Create_DateTime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(Long value1, Long value2) {
            addCriterion("Create_DateTime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(Long value1, Long value2) {
            addCriterion("Create_DateTime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("Update_DateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("Update_DateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(Long value) {
            addCriterion("Update_DateTime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(Long value) {
            addCriterion("Update_DateTime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(Long value) {
            addCriterion("Update_DateTime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("Update_DateTime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(Long value) {
            addCriterion("Update_DateTime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(Long value) {
            addCriterion("Update_DateTime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<Long> values) {
            addCriterion("Update_DateTime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<Long> values) {
            addCriterion("Update_DateTime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(Long value1, Long value2) {
            addCriterion("Update_DateTime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(Long value1, Long value2) {
            addCriterion("Update_DateTime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNull() {
            addCriterion("Record_Status is null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNotNull() {
            addCriterion("Record_Status is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusEqualTo(Integer value) {
            addCriterion("Record_Status =", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotEqualTo(Integer value) {
            addCriterion("Record_Status <>", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThan(Integer value) {
            addCriterion("Record_Status >", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Record_Status >=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThan(Integer value) {
            addCriterion("Record_Status <", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Record_Status <=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIn(List<Integer> values) {
            addCriterion("Record_Status in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotIn(List<Integer> values) {
            addCriterion("Record_Status not in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusBetween(Integer value1, Integer value2) {
            addCriterion("Record_Status between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Record_Status not between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusIsNull() {
            addCriterion("Active_Status is null");
            return (Criteria) this;
        }

        public Criteria andActiveStatusIsNotNull() {
            addCriterion("Active_Status is not null");
            return (Criteria) this;
        }

        public Criteria andActiveStatusEqualTo(Integer value) {
            addCriterion("Active_Status =", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusNotEqualTo(Integer value) {
            addCriterion("Active_Status <>", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusGreaterThan(Integer value) {
            addCriterion("Active_Status >", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Active_Status >=", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusLessThan(Integer value) {
            addCriterion("Active_Status <", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Active_Status <=", value, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusIn(List<Integer> values) {
            addCriterion("Active_Status in", values, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusNotIn(List<Integer> values) {
            addCriterion("Active_Status not in", values, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusBetween(Integer value1, Integer value2) {
            addCriterion("Active_Status between", value1, value2, "activeStatus");
            return (Criteria) this;
        }

        public Criteria andActiveStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Active_Status not between", value1, value2, "activeStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_hotel
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asp_hotel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}