package com.ctrip.asp.commom.dao.auto.model;

public class AspPmsRoute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_pms_route.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_pms_route.ApiKey
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String apikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_pms_route.URL
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_pms_route.License
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asp_pms_route.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Byte recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_pms_route.ID
     *
     * @return the value of asp_pms_route.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_pms_route.ID
     *
     * @param id the value for asp_pms_route.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_pms_route.ApiKey
     *
     * @return the value of asp_pms_route.ApiKey
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_pms_route.ApiKey
     *
     * @param apikey the value for asp_pms_route.ApiKey
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setApikey(String apikey) {
        this.apikey = apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_pms_route.URL
     *
     * @return the value of asp_pms_route.URL
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_pms_route.URL
     *
     * @param url the value for asp_pms_route.URL
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_pms_route.License
     *
     * @return the value of asp_pms_route.License
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_pms_route.License
     *
     * @param license the value for asp_pms_route.License
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setLicense(String license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asp_pms_route.Record_Status
     *
     * @return the value of asp_pms_route.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Byte getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asp_pms_route.Record_Status
     *
     * @param recordStatus the value for asp_pms_route.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Byte recordStatus) {
        this.recordStatus = recordStatus;
    }
}