package com.ctrip.asp.commom.dao.auto.model;

public class InInvoicenotifyRqLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicenotify_rq_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicenotify_rq_log.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicenotify_rq_log.InvoiceNotify_RQ
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String invoicenotifyRq;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicenotify_rq_log.UniqueID
     *
     * @return the value of in_invoicenotify_rq_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicenotify_rq_log.UniqueID
     *
     * @param uniqueid the value for in_invoicenotify_rq_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicenotify_rq_log.Type
     *
     * @return the value of in_invoicenotify_rq_log.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicenotify_rq_log.Type
     *
     * @param type the value for in_invoicenotify_rq_log.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicenotify_rq_log.InvoiceNotify_RQ
     *
     * @return the value of in_invoicenotify_rq_log.InvoiceNotify_RQ
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getInvoicenotifyRq() {
        return invoicenotifyRq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicenotify_rq_log.InvoiceNotify_RQ
     *
     * @param invoicenotifyRq the value for in_invoicenotify_rq_log.InvoiceNotify_RQ
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setInvoicenotifyRq(String invoicenotifyRq) {
        this.invoicenotifyRq = invoicenotifyRq;
    }
}