package com.ctrip.asp.commom.dao.auto.model;

public class InInvoicebooking {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.channelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.pmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.hotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.orderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.otaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String otaorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.serialNumber
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String serialnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.isPull
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer ispull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.invoiceStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer invoicestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.note
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.guestName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String guestname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.guestIdNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String guestidno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.guestMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String guestmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.invoiceType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer invoicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.invoiceTitle
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String invoicetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.companyTel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String companytel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.companyAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String companyaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.taxID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String taxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.bankName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.bankAccount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String bankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.wantTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String wanttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.postType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer posttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.receiverName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String receivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.receiverMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String receivermobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.receiverAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String receiveraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.resultCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer resultcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.createDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.updateDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long updatedatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicebooking.recordStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.id
     *
     * @return the value of in_invoicebooking.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.id
     *
     * @param id the value for in_invoicebooking.id
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.channelCode
     *
     * @return the value of in_invoicebooking.channelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.channelCode
     *
     * @param channelcode the value for in_invoicebooking.channelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.pmsCode
     *
     * @return the value of in_invoicebooking.pmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmscode() {
        return pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.pmsCode
     *
     * @param pmscode the value for in_invoicebooking.pmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmscode(String pmscode) {
        this.pmscode = pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.hotelCode
     *
     * @return the value of in_invoicebooking.hotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelcode() {
        return hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.hotelCode
     *
     * @param hotelcode the value for in_invoicebooking.hotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelcode(String hotelcode) {
        this.hotelcode = hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.orderNo
     *
     * @return the value of in_invoicebooking.orderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.orderNo
     *
     * @param orderno the value for in_invoicebooking.orderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.otaOrderNo
     *
     * @return the value of in_invoicebooking.otaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOtaorderno() {
        return otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.otaOrderNo
     *
     * @param otaorderno the value for in_invoicebooking.otaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOtaorderno(String otaorderno) {
        this.otaorderno = otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.serialNumber
     *
     * @return the value of in_invoicebooking.serialNumber
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.serialNumber
     *
     * @param serialnumber the value for in_invoicebooking.serialNumber
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.type
     *
     * @return the value of in_invoicebooking.type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.type
     *
     * @param type the value for in_invoicebooking.type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.isPull
     *
     * @return the value of in_invoicebooking.isPull
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIspull() {
        return ispull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.isPull
     *
     * @param ispull the value for in_invoicebooking.isPull
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIspull(Integer ispull) {
        this.ispull = ispull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.invoiceStatus
     *
     * @return the value of in_invoicebooking.invoiceStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getInvoicestatus() {
        return invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.invoiceStatus
     *
     * @param invoicestatus the value for in_invoicebooking.invoiceStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setInvoicestatus(Integer invoicestatus) {
        this.invoicestatus = invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.note
     *
     * @return the value of in_invoicebooking.note
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.note
     *
     * @param note the value for in_invoicebooking.note
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.guestName
     *
     * @return the value of in_invoicebooking.guestName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getGuestname() {
        return guestname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.guestName
     *
     * @param guestname the value for in_invoicebooking.guestName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setGuestname(String guestname) {
        this.guestname = guestname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.guestIdNo
     *
     * @return the value of in_invoicebooking.guestIdNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getGuestidno() {
        return guestidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.guestIdNo
     *
     * @param guestidno the value for in_invoicebooking.guestIdNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setGuestidno(String guestidno) {
        this.guestidno = guestidno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.guestMobile
     *
     * @return the value of in_invoicebooking.guestMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getGuestmobile() {
        return guestmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.guestMobile
     *
     * @param guestmobile the value for in_invoicebooking.guestMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setGuestmobile(String guestmobile) {
        this.guestmobile = guestmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.invoiceType
     *
     * @return the value of in_invoicebooking.invoiceType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getInvoicetype() {
        return invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.invoiceType
     *
     * @param invoicetype the value for in_invoicebooking.invoiceType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setInvoicetype(Integer invoicetype) {
        this.invoicetype = invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.invoiceTitle
     *
     * @return the value of in_invoicebooking.invoiceTitle
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getInvoicetitle() {
        return invoicetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.invoiceTitle
     *
     * @param invoicetitle the value for in_invoicebooking.invoiceTitle
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setInvoicetitle(String invoicetitle) {
        this.invoicetitle = invoicetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.companyTel
     *
     * @return the value of in_invoicebooking.companyTel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getCompanytel() {
        return companytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.companyTel
     *
     * @param companytel the value for in_invoicebooking.companyTel
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCompanytel(String companytel) {
        this.companytel = companytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.companyAddress
     *
     * @return the value of in_invoicebooking.companyAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.companyAddress
     *
     * @param companyaddress the value for in_invoicebooking.companyAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.taxID
     *
     * @return the value of in_invoicebooking.taxID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getTaxid() {
        return taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.taxID
     *
     * @param taxid the value for in_invoicebooking.taxID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setTaxid(String taxid) {
        this.taxid = taxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.bankName
     *
     * @return the value of in_invoicebooking.bankName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.bankName
     *
     * @param bankname the value for in_invoicebooking.bankName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.bankAccount
     *
     * @return the value of in_invoicebooking.bankAccount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.bankAccount
     *
     * @param bankaccount the value for in_invoicebooking.bankAccount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.email
     *
     * @return the value of in_invoicebooking.email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.email
     *
     * @param email the value for in_invoicebooking.email
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.wantTime
     *
     * @return the value of in_invoicebooking.wantTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getWanttime() {
        return wanttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.wantTime
     *
     * @param wanttime the value for in_invoicebooking.wantTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setWanttime(String wanttime) {
        this.wanttime = wanttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.postType
     *
     * @return the value of in_invoicebooking.postType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getPosttype() {
        return posttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.postType
     *
     * @param posttype the value for in_invoicebooking.postType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPosttype(Integer posttype) {
        this.posttype = posttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.receiverName
     *
     * @return the value of in_invoicebooking.receiverName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.receiverName
     *
     * @param receivername the value for in_invoicebooking.receiverName
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.receiverMobile
     *
     * @return the value of in_invoicebooking.receiverMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getReceivermobile() {
        return receivermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.receiverMobile
     *
     * @param receivermobile the value for in_invoicebooking.receiverMobile
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setReceivermobile(String receivermobile) {
        this.receivermobile = receivermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.receiverAddress
     *
     * @return the value of in_invoicebooking.receiverAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.receiverAddress
     *
     * @param receiveraddress the value for in_invoicebooking.receiverAddress
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.resultCode
     *
     * @return the value of in_invoicebooking.resultCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getResultcode() {
        return resultcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.resultCode
     *
     * @param resultcode the value for in_invoicebooking.resultCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setResultcode(Integer resultcode) {
        this.resultcode = resultcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.createDateTime
     *
     * @return the value of in_invoicebooking.createDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreatedatetime() {
        return createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.createDateTime
     *
     * @param createdatetime the value for in_invoicebooking.createDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreatedatetime(Long createdatetime) {
        this.createdatetime = createdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.updateDateTime
     *
     * @return the value of in_invoicebooking.updateDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getUpdatedatetime() {
        return updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.updateDateTime
     *
     * @param updatedatetime the value for in_invoicebooking.updateDateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdatedatetime(Long updatedatetime) {
        this.updatedatetime = updatedatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicebooking.recordStatus
     *
     * @return the value of in_invoicebooking.recordStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordstatus() {
        return recordstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicebooking.recordStatus
     *
     * @param recordstatus the value for in_invoicebooking.recordStatus
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordstatus(Integer recordstatus) {
        this.recordstatus = recordstatus;
    }
}