package com.ctrip.asp.commom.dao.auto.model;

import java.util.ArrayList;
import java.util.List;

public class InInvoicesearchLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public InInvoicesearchLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUniqueidIsNull() {
            addCriterion("UniqueID is null");
            return (Criteria) this;
        }

        public Criteria andUniqueidIsNotNull() {
            addCriterion("UniqueID is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueidEqualTo(String value) {
            addCriterion("UniqueID =", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotEqualTo(String value) {
            addCriterion("UniqueID <>", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidGreaterThan(String value) {
            addCriterion("UniqueID >", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidGreaterThanOrEqualTo(String value) {
            addCriterion("UniqueID >=", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLessThan(String value) {
            addCriterion("UniqueID <", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLessThanOrEqualTo(String value) {
            addCriterion("UniqueID <=", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidLike(String value) {
            addCriterion("UniqueID like", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotLike(String value) {
            addCriterion("UniqueID not like", value, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidIn(List<String> values) {
            addCriterion("UniqueID in", values, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotIn(List<String> values) {
            addCriterion("UniqueID not in", values, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidBetween(String value1, String value2) {
            addCriterion("UniqueID between", value1, value2, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andUniqueidNotBetween(String value1, String value2) {
            addCriterion("UniqueID not between", value1, value2, "uniqueid");
            return (Criteria) this;
        }

        public Criteria andChannelcodeIsNull() {
            addCriterion("ChannelCode is null");
            return (Criteria) this;
        }

        public Criteria andChannelcodeIsNotNull() {
            addCriterion("ChannelCode is not null");
            return (Criteria) this;
        }

        public Criteria andChannelcodeEqualTo(String value) {
            addCriterion("ChannelCode =", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotEqualTo(String value) {
            addCriterion("ChannelCode <>", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeGreaterThan(String value) {
            addCriterion("ChannelCode >", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ChannelCode >=", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeLessThan(String value) {
            addCriterion("ChannelCode <", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeLessThanOrEqualTo(String value) {
            addCriterion("ChannelCode <=", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeLike(String value) {
            addCriterion("ChannelCode like", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotLike(String value) {
            addCriterion("ChannelCode not like", value, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeIn(List<String> values) {
            addCriterion("ChannelCode in", values, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotIn(List<String> values) {
            addCriterion("ChannelCode not in", values, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeBetween(String value1, String value2) {
            addCriterion("ChannelCode between", value1, value2, "channelcode");
            return (Criteria) this;
        }

        public Criteria andChannelcodeNotBetween(String value1, String value2) {
            addCriterion("ChannelCode not between", value1, value2, "channelcode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNull() {
            addCriterion("Pms_Code is null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIsNotNull() {
            addCriterion("Pms_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPmsCodeEqualTo(String value) {
            addCriterion("Pms_Code =", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotEqualTo(String value) {
            addCriterion("Pms_Code <>", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThan(String value) {
            addCriterion("Pms_Code >", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Pms_Code >=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThan(String value) {
            addCriterion("Pms_Code <", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLessThanOrEqualTo(String value) {
            addCriterion("Pms_Code <=", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeLike(String value) {
            addCriterion("Pms_Code like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotLike(String value) {
            addCriterion("Pms_Code not like", value, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeIn(List<String> values) {
            addCriterion("Pms_Code in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotIn(List<String> values) {
            addCriterion("Pms_Code not in", values, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeBetween(String value1, String value2) {
            addCriterion("Pms_Code between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andPmsCodeNotBetween(String value1, String value2) {
            addCriterion("Pms_Code not between", value1, value2, "pmsCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNull() {
            addCriterion("Hotel_Code is null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIsNotNull() {
            addCriterion("Hotel_Code is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCodeEqualTo(String value) {
            addCriterion("Hotel_Code =", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotEqualTo(String value) {
            addCriterion("Hotel_Code <>", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThan(String value) {
            addCriterion("Hotel_Code >", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_Code >=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThan(String value) {
            addCriterion("Hotel_Code <", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLessThanOrEqualTo(String value) {
            addCriterion("Hotel_Code <=", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeLike(String value) {
            addCriterion("Hotel_Code like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotLike(String value) {
            addCriterion("Hotel_Code not like", value, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeIn(List<String> values) {
            addCriterion("Hotel_Code in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotIn(List<String> values) {
            addCriterion("Hotel_Code not in", values, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeBetween(String value1, String value2) {
            addCriterion("Hotel_Code between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andHotelCodeNotBetween(String value1, String value2) {
            addCriterion("Hotel_Code not between", value1, value2, "hotelCode");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNull() {
            addCriterion("OrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOrdernoIsNotNull() {
            addCriterion("OrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOrdernoEqualTo(String value) {
            addCriterion("OrderNo =", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotEqualTo(String value) {
            addCriterion("OrderNo <>", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThan(String value) {
            addCriterion("OrderNo >", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoGreaterThanOrEqualTo(String value) {
            addCriterion("OrderNo >=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThan(String value) {
            addCriterion("OrderNo <", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLessThanOrEqualTo(String value) {
            addCriterion("OrderNo <=", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoLike(String value) {
            addCriterion("OrderNo like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotLike(String value) {
            addCriterion("OrderNo not like", value, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoIn(List<String> values) {
            addCriterion("OrderNo in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotIn(List<String> values) {
            addCriterion("OrderNo not in", values, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoBetween(String value1, String value2) {
            addCriterion("OrderNo between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOrdernoNotBetween(String value1, String value2) {
            addCriterion("OrderNo not between", value1, value2, "orderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoIsNull() {
            addCriterion("OtaOrderNo is null");
            return (Criteria) this;
        }

        public Criteria andOtaordernoIsNotNull() {
            addCriterion("OtaOrderNo is not null");
            return (Criteria) this;
        }

        public Criteria andOtaordernoEqualTo(String value) {
            addCriterion("OtaOrderNo =", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoNotEqualTo(String value) {
            addCriterion("OtaOrderNo <>", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoGreaterThan(String value) {
            addCriterion("OtaOrderNo >", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoGreaterThanOrEqualTo(String value) {
            addCriterion("OtaOrderNo >=", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoLessThan(String value) {
            addCriterion("OtaOrderNo <", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoLessThanOrEqualTo(String value) {
            addCriterion("OtaOrderNo <=", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoLike(String value) {
            addCriterion("OtaOrderNo like", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoNotLike(String value) {
            addCriterion("OtaOrderNo not like", value, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoIn(List<String> values) {
            addCriterion("OtaOrderNo in", values, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoNotIn(List<String> values) {
            addCriterion("OtaOrderNo not in", values, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoBetween(String value1, String value2) {
            addCriterion("OtaOrderNo between", value1, value2, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andOtaordernoNotBetween(String value1, String value2) {
            addCriterion("OtaOrderNo not between", value1, value2, "otaorderno");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNull() {
            addCriterion("Result_Code is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNotNull() {
            addCriterion("Result_Code is not null");
            return (Criteria) this;
        }

        public Criteria andResultCodeEqualTo(Integer value) {
            addCriterion("Result_Code =", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotEqualTo(Integer value) {
            addCriterion("Result_Code <>", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThan(Integer value) {
            addCriterion("Result_Code >", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Result_Code >=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThan(Integer value) {
            addCriterion("Result_Code <", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThanOrEqualTo(Integer value) {
            addCriterion("Result_Code <=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeIn(List<Integer> values) {
            addCriterion("Result_Code in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotIn(List<Integer> values) {
            addCriterion("Result_Code not in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeBetween(Integer value1, Integer value2) {
            addCriterion("Result_Code between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("Result_Code not between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultMessageIsNull() {
            addCriterion("Result_Message is null");
            return (Criteria) this;
        }

        public Criteria andResultMessageIsNotNull() {
            addCriterion("Result_Message is not null");
            return (Criteria) this;
        }

        public Criteria andResultMessageEqualTo(String value) {
            addCriterion("Result_Message =", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageNotEqualTo(String value) {
            addCriterion("Result_Message <>", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageGreaterThan(String value) {
            addCriterion("Result_Message >", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageGreaterThanOrEqualTo(String value) {
            addCriterion("Result_Message >=", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageLessThan(String value) {
            addCriterion("Result_Message <", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageLessThanOrEqualTo(String value) {
            addCriterion("Result_Message <=", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageLike(String value) {
            addCriterion("Result_Message like", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageNotLike(String value) {
            addCriterion("Result_Message not like", value, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageIn(List<String> values) {
            addCriterion("Result_Message in", values, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageNotIn(List<String> values) {
            addCriterion("Result_Message not in", values, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageBetween(String value1, String value2) {
            addCriterion("Result_Message between", value1, value2, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andResultMessageNotBetween(String value1, String value2) {
            addCriterion("Result_Message not between", value1, value2, "resultMessage");
            return (Criteria) this;
        }

        public Criteria andCosttimeIsNull() {
            addCriterion("CostTime is null");
            return (Criteria) this;
        }

        public Criteria andCosttimeIsNotNull() {
            addCriterion("CostTime is not null");
            return (Criteria) this;
        }

        public Criteria andCosttimeEqualTo(Integer value) {
            addCriterion("CostTime =", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeNotEqualTo(Integer value) {
            addCriterion("CostTime <>", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeGreaterThan(Integer value) {
            addCriterion("CostTime >", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("CostTime >=", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeLessThan(Integer value) {
            addCriterion("CostTime <", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeLessThanOrEqualTo(Integer value) {
            addCriterion("CostTime <=", value, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeIn(List<Integer> values) {
            addCriterion("CostTime in", values, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeNotIn(List<Integer> values) {
            addCriterion("CostTime not in", values, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeBetween(Integer value1, Integer value2) {
            addCriterion("CostTime between", value1, value2, "costtime");
            return (Criteria) this;
        }

        public Criteria andCosttimeNotBetween(Integer value1, Integer value2) {
            addCriterion("CostTime not between", value1, value2, "costtime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("Create_DateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("Create_DateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(Long value) {
            addCriterion("Create_DateTime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Long value) {
            addCriterion("Create_DateTime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(Long value) {
            addCriterion("Create_DateTime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Long value) {
            addCriterion("Create_DateTime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(Long value) {
            addCriterion("Create_DateTime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Long value) {
            addCriterion("Create_DateTime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<Long> values) {
            addCriterion("Create_DateTime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<Long> values) {
            addCriterion("Create_DateTime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(Long value1, Long value2) {
            addCriterion("Create_DateTime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(Long value1, Long value2) {
            addCriterion("Create_DateTime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNull() {
            addCriterion("Record_Status is null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIsNotNull() {
            addCriterion("Record_Status is not null");
            return (Criteria) this;
        }

        public Criteria andRecordStatusEqualTo(Integer value) {
            addCriterion("Record_Status =", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotEqualTo(Integer value) {
            addCriterion("Record_Status <>", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThan(Integer value) {
            addCriterion("Record_Status >", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Record_Status >=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThan(Integer value) {
            addCriterion("Record_Status <", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Record_Status <=", value, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusIn(List<Integer> values) {
            addCriterion("Record_Status in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotIn(List<Integer> values) {
            addCriterion("Record_Status not in", values, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusBetween(Integer value1, Integer value2) {
            addCriterion("Record_Status between", value1, value2, "recordStatus");
            return (Criteria) this;
        }

        public Criteria andRecordStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Record_Status not between", value1, value2, "recordStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table in_invoicesearch_log
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}