package com.ctrip.asp.commom.dao.auto.model;

public class InInvoicesearchLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String otaorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Result_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Result_Message
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String resultMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.CostTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer costtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column in_invoicesearch_log.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.ID
     *
     * @return the value of in_invoicesearch_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.ID
     *
     * @param id the value for in_invoicesearch_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.UniqueID
     *
     * @return the value of in_invoicesearch_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.UniqueID
     *
     * @param uniqueid the value for in_invoicesearch_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.ChannelCode
     *
     * @return the value of in_invoicesearch_log.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.ChannelCode
     *
     * @param channelcode the value for in_invoicesearch_log.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Pms_Code
     *
     * @return the value of in_invoicesearch_log.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Pms_Code
     *
     * @param pmsCode the value for in_invoicesearch_log.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Hotel_Code
     *
     * @return the value of in_invoicesearch_log.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Hotel_Code
     *
     * @param hotelCode the value for in_invoicesearch_log.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.OrderNo
     *
     * @return the value of in_invoicesearch_log.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.OrderNo
     *
     * @param orderno the value for in_invoicesearch_log.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.OtaOrderNo
     *
     * @return the value of in_invoicesearch_log.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOtaorderno() {
        return otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.OtaOrderNo
     *
     * @param otaorderno the value for in_invoicesearch_log.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOtaorderno(String otaorderno) {
        this.otaorderno = otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Result_Code
     *
     * @return the value of in_invoicesearch_log.Result_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Result_Code
     *
     * @param resultCode the value for in_invoicesearch_log.Result_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setResultCode(Integer resultCode) {
        this.resultCode = resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Result_Message
     *
     * @return the value of in_invoicesearch_log.Result_Message
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getResultMessage() {
        return resultMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Result_Message
     *
     * @param resultMessage the value for in_invoicesearch_log.Result_Message
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setResultMessage(String resultMessage) {
        this.resultMessage = resultMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.CostTime
     *
     * @return the value of in_invoicesearch_log.CostTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getCosttime() {
        return costtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.CostTime
     *
     * @param costtime the value for in_invoicesearch_log.CostTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCosttime(Integer costtime) {
        this.costtime = costtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Create_DateTime
     *
     * @return the value of in_invoicesearch_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Create_DateTime
     *
     * @param createDatetime the value for in_invoicesearch_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Long createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column in_invoicesearch_log.Record_Status
     *
     * @return the value of in_invoicesearch_log.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column in_invoicesearch_log.Record_Status
     *
     * @param recordStatus the value for in_invoicesearch_log.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}