package com.ctrip.asp.commom.dao.auto.model;

public class JobConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_config.Job_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_config.Job_Condition
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String jobCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_config.Job_Info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String jobInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_config.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_config.Job_Name
     *
     * @return the value of job_config.Job_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_config.Job_Name
     *
     * @param jobName the value for job_config.Job_Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_config.Job_Condition
     *
     * @return the value of job_config.Job_Condition
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getJobCondition() {
        return jobCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_config.Job_Condition
     *
     * @param jobCondition the value for job_config.Job_Condition
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setJobCondition(String jobCondition) {
        this.jobCondition = jobCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_config.Job_Info
     *
     * @return the value of job_config.Job_Info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getJobInfo() {
        return jobInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_config.Job_Info
     *
     * @param jobInfo the value for job_config.Job_Info
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setJobInfo(String jobInfo) {
        this.jobInfo = jobInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_config.Record_Status
     *
     * @return the value of job_config.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_config.Record_Status
     *
     * @param recordStatus the value for job_config.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}