package com.ctrip.asp.commom.dao.auto.model;

import java.util.Date;

public class MapRoomBuildRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String mapid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.FLOOR_BD_ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String floorBdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String poiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Area
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Double area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Point
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Geometry
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String geometry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_build_room.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.ID
     *
     * @return the value of map_room_build_room.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.ID
     *
     * @param id the value for map_room_build_room.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.MapID
     *
     * @return the value of map_room_build_room.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getMapid() {
        return mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.MapID
     *
     * @param mapid the value for map_room_build_room.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setMapid(String mapid) {
        this.mapid = mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.FLOOR_BD_ID
     *
     * @return the value of map_room_build_room.FLOOR_BD_ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getFloorBdId() {
        return floorBdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.FLOOR_BD_ID
     *
     * @param floorBdId the value for map_room_build_room.FLOOR_BD_ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setFloorBdId(String floorBdId) {
        this.floorBdId = floorBdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Name
     *
     * @return the value of map_room_build_room.Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Name
     *
     * @param name the value for map_room_build_room.Name
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.PoiID
     *
     * @return the value of map_room_build_room.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPoiid() {
        return poiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.PoiID
     *
     * @param poiid the value for map_room_build_room.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPoiid(String poiid) {
        this.poiid = poiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Num
     *
     * @return the value of map_room_build_room.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Num
     *
     * @param num the value for map_room_build_room.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Area
     *
     * @return the value of map_room_build_room.Area
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Double getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Area
     *
     * @param area the value for map_room_build_room.Area
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setArea(Double area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Point
     *
     * @return the value of map_room_build_room.Point
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Point
     *
     * @param point the value for map_room_build_room.Point
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPoint(String point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Geometry
     *
     * @return the value of map_room_build_room.Geometry
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getGeometry() {
        return geometry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Geometry
     *
     * @param geometry the value for map_room_build_room.Geometry
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setGeometry(String geometry) {
        this.geometry = geometry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Create_DateTime
     *
     * @return the value of map_room_build_room.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Create_DateTime
     *
     * @param createDatetime the value for map_room_build_room.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Update_DateTime
     *
     * @return the value of map_room_build_room.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Update_DateTime
     *
     * @param updateDatetime the value for map_room_build_room.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Record_Status
     *
     * @return the value of map_room_build_room.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Record_Status
     *
     * @param recordStatus the value for map_room_build_room.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_build_room.Type
     *
     * @return the value of map_room_build_room.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_build_room.Type
     *
     * @param type the value for map_room_build_room.Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }
}