package com.ctrip.asp.commom.dao.auto.model;

import java.util.Date;

public class MapRoomMapping {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String mapid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String poiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map_room_mapping.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.ID
     *
     * @return the value of map_room_mapping.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.ID
     *
     * @param id the value for map_room_mapping.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.MapID
     *
     * @return the value of map_room_mapping.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getMapid() {
        return mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.MapID
     *
     * @param mapid the value for map_room_mapping.MapID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setMapid(String mapid) {
        this.mapid = mapid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.PoiID
     *
     * @return the value of map_room_mapping.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPoiid() {
        return poiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.PoiID
     *
     * @param poiid the value for map_room_mapping.PoiID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPoiid(String poiid) {
        this.poiid = poiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.Num
     *
     * @return the value of map_room_mapping.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.Num
     *
     * @param num the value for map_room_mapping.Num
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.RoomID
     *
     * @return the value of map_room_mapping.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.RoomID
     *
     * @param roomid the value for map_room_mapping.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.RoomNo
     *
     * @return the value of map_room_mapping.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.RoomNo
     *
     * @param roomno the value for map_room_mapping.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.Create_DateTime
     *
     * @return the value of map_room_mapping.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.Create_DateTime
     *
     * @param createDatetime the value for map_room_mapping.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.Update_DateTime
     *
     * @return the value of map_room_mapping.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.Update_DateTime
     *
     * @param updateDatetime the value for map_room_mapping.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map_room_mapping.Record_Status
     *
     * @return the value of map_room_mapping.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map_room_mapping.Record_Status
     *
     * @param recordStatus the value for map_room_mapping.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}