package com.ctrip.asp.commom.dao.auto.model;

public class SrHotelRoomRestriction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Room_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer roomStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Active_Date
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long activeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_hotel_room_restriction.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.ID
     *
     * @return the value of sr_hotel_room_restriction.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.ID
     *
     * @param id the value for sr_hotel_room_restriction.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Pms_Code
     *
     * @return the value of sr_hotel_room_restriction.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Pms_Code
     *
     * @param pmsCode the value for sr_hotel_room_restriction.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Hotel_Code
     *
     * @return the value of sr_hotel_room_restriction.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Hotel_Code
     *
     * @param hotelCode the value for sr_hotel_room_restriction.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Room_Type_Code
     *
     * @return the value of sr_hotel_room_restriction.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Room_Type_Code
     *
     * @param roomTypeCode the value for sr_hotel_room_restriction.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.RoomID
     *
     * @return the value of sr_hotel_room_restriction.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.RoomID
     *
     * @param roomid the value for sr_hotel_room_restriction.RoomID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.RoomNo
     *
     * @return the value of sr_hotel_room_restriction.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.RoomNo
     *
     * @param roomno the value for sr_hotel_room_restriction.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Room_Status
     *
     * @return the value of sr_hotel_room_restriction.Room_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRoomStatus() {
        return roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Room_Status
     *
     * @param roomStatus the value for sr_hotel_room_restriction.Room_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomStatus(Integer roomStatus) {
        this.roomStatus = roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Active_Date
     *
     * @return the value of sr_hotel_room_restriction.Active_Date
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getActiveDate() {
        return activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Active_Date
     *
     * @param activeDate the value for sr_hotel_room_restriction.Active_Date
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setActiveDate(Long activeDate) {
        this.activeDate = activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Create_DateTime
     *
     * @return the value of sr_hotel_room_restriction.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Create_DateTime
     *
     * @param createDatetime the value for sr_hotel_room_restriction.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Long createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Update_DateTime
     *
     * @return the value of sr_hotel_room_restriction.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Update_DateTime
     *
     * @param updateDatetime the value for sr_hotel_room_restriction.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdateDatetime(Long updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_hotel_room_restriction.Record_Status
     *
     * @return the value of sr_hotel_room_restriction.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_hotel_room_restriction.Record_Status
     *
     * @param recordStatus the value for sr_hotel_room_restriction.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}