package com.ctrip.asp.commom.dao.auto.model;

public class SrRoomstatusRsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_roomstatus_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_roomstatus_rs_log.Room_Status_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomStatusRs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_roomstatus_rs_log.UniqueID
     *
     * @return the value of sr_roomstatus_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_roomstatus_rs_log.UniqueID
     *
     * @param uniqueid the value for sr_roomstatus_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_roomstatus_rs_log.Room_Status_RS
     *
     * @return the value of sr_roomstatus_rs_log.Room_Status_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomStatusRs() {
        return roomStatusRs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_roomstatus_rs_log.Room_Status_RS
     *
     * @param roomStatusRs the value for sr_roomstatus_rs_log.Room_Status_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomStatusRs(String roomStatusRs) {
        this.roomStatusRs = roomStatusRs;
    }
}