package com.ctrip.asp.commom.dao.auto.model;

public class SrSelectorderRsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectorder_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String uniqueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectorder_rs_log.SelectOrder_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String selectorderRs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectorder_rs_log.UniqueID
     *
     * @return the value of sr_selectorder_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getUniqueid() {
        return uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectorder_rs_log.UniqueID
     *
     * @param uniqueid the value for sr_selectorder_rs_log.UniqueID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectorder_rs_log.SelectOrder_RS
     *
     * @return the value of sr_selectorder_rs_log.SelectOrder_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getSelectorderRs() {
        return selectorderRs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectorder_rs_log.SelectOrder_RS
     *
     * @param selectorderRs the value for sr_selectorder_rs_log.SelectOrder_RS
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setSelectorderRs(String selectorderRs) {
        this.selectorderRs = selectorderRs;
    }
}