package com.ctrip.asp.commom.dao.auto.model;

import java.util.Date;

public class SrSelectroomInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String otaorderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String channelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.CheckIn
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date checkin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.CheckOut
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date checkout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.BuildingNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String buildingno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.FloorNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String floorno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.OTA_Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer otaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sr_selectroom_info.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.ID
     *
     * @return the value of sr_selectroom_info.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.ID
     *
     * @param id the value for sr_selectroom_info.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.OrderNo
     *
     * @return the value of sr_selectroom_info.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.OrderNo
     *
     * @param orderno the value for sr_selectroom_info.OrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.OtaOrderNo
     *
     * @return the value of sr_selectroom_info.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getOtaorderno() {
        return otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.OtaOrderNo
     *
     * @param otaorderno the value for sr_selectroom_info.OtaOrderNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOtaorderno(String otaorderno) {
        this.otaorderno = otaorderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.ChannelCode
     *
     * @return the value of sr_selectroom_info.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getChannelcode() {
        return channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.ChannelCode
     *
     * @param channelcode the value for sr_selectroom_info.ChannelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChannelcode(String channelcode) {
        this.channelcode = channelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Pms_Code
     *
     * @return the value of sr_selectroom_info.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Pms_Code
     *
     * @param pmsCode the value for sr_selectroom_info.Pms_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Hotel_Code
     *
     * @return the value of sr_selectroom_info.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelCode() {
        return hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Hotel_Code
     *
     * @param hotelCode the value for sr_selectroom_info.Hotel_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelCode(String hotelCode) {
        this.hotelCode = hotelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Room_Type_Code
     *
     * @return the value of sr_selectroom_info.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomTypeCode() {
        return roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Room_Type_Code
     *
     * @param roomTypeCode the value for sr_selectroom_info.Room_Type_Code
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomTypeCode(String roomTypeCode) {
        this.roomTypeCode = roomTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.CheckIn
     *
     * @return the value of sr_selectroom_info.CheckIn
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getCheckin() {
        return checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.CheckIn
     *
     * @param checkin the value for sr_selectroom_info.CheckIn
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCheckin(Date checkin) {
        this.checkin = checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.CheckOut
     *
     * @return the value of sr_selectroom_info.CheckOut
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getCheckout() {
        return checkout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.CheckOut
     *
     * @param checkout the value for sr_selectroom_info.CheckOut
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCheckout(Date checkout) {
        this.checkout = checkout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.BuildingNo
     *
     * @return the value of sr_selectroom_info.BuildingNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getBuildingno() {
        return buildingno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.BuildingNo
     *
     * @param buildingno the value for sr_selectroom_info.BuildingNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setBuildingno(String buildingno) {
        this.buildingno = buildingno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.FloorNo
     *
     * @return the value of sr_selectroom_info.FloorNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getFloorno() {
        return floorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.FloorNo
     *
     * @param floorno the value for sr_selectroom_info.FloorNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setFloorno(String floorno) {
        this.floorno = floorno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.RoomNo
     *
     * @return the value of sr_selectroom_info.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.RoomNo
     *
     * @param roomno the value for sr_selectroom_info.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.OTA_Type
     *
     * @return the value of sr_selectroom_info.OTA_Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getOtaType() {
        return otaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.OTA_Type
     *
     * @param otaType the value for sr_selectroom_info.OTA_Type
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setOtaType(Integer otaType) {
        this.otaType = otaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Create_DateTime
     *
     * @return the value of sr_selectroom_info.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Create_DateTime
     *
     * @param createDatetime the value for sr_selectroom_info.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Long createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Update_DateTime
     *
     * @return the value of sr_selectroom_info.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Update_DateTime
     *
     * @param updateDatetime the value for sr_selectroom_info.Update_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setUpdateDatetime(Long updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sr_selectroom_info.Record_Status
     *
     * @return the value of sr_selectroom_info.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sr_selectroom_info.Record_Status
     *
     * @param recordStatus the value for sr_selectroom_info.Record_Status
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}