package com.ctrip.asp.commom.dao.auto.model;

import java.util.Date;

public class UcRoomalertStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.StartDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.EndDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.CheckIn_Days
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Byte checkinDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_statistics.RoomPower
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long roompower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.ID
     *
     * @return the value of uc_roomalert_statistics.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.ID
     *
     * @param id the value for uc_roomalert_statistics.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.StartDate
     *
     * @return the value of uc_roomalert_statistics.StartDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.StartDate
     *
     * @param startdate the value for uc_roomalert_statistics.StartDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.EndDate
     *
     * @return the value of uc_roomalert_statistics.EndDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.EndDate
     *
     * @param enddate the value for uc_roomalert_statistics.EndDate
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.PmsCode
     *
     * @return the value of uc_roomalert_statistics.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmscode() {
        return pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.PmsCode
     *
     * @param pmscode the value for uc_roomalert_statistics.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmscode(String pmscode) {
        this.pmscode = pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.HotelCode
     *
     * @return the value of uc_roomalert_statistics.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelcode() {
        return hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.HotelCode
     *
     * @param hotelcode the value for uc_roomalert_statistics.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelcode(String hotelcode) {
        this.hotelcode = hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.RoomNo
     *
     * @return the value of uc_roomalert_statistics.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.RoomNo
     *
     * @param roomno the value for uc_roomalert_statistics.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.CheckIn_Days
     *
     * @return the value of uc_roomalert_statistics.CheckIn_Days
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Byte getCheckinDays() {
        return checkinDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.CheckIn_Days
     *
     * @param checkinDays the value for uc_roomalert_statistics.CheckIn_Days
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCheckinDays(Byte checkinDays) {
        this.checkinDays = checkinDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_statistics.RoomPower
     *
     * @return the value of uc_roomalert_statistics.RoomPower
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getRoompower() {
        return roompower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_statistics.RoomPower
     *
     * @param roompower the value for uc_roomalert_statistics.RoomPower
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoompower(Long roompower) {
        this.roompower = roompower;
    }
}