package com.ctrip.asp.commom.dao.auto.model;

public class UcRoomalertLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String pmscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String hotelcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private String roomno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.IsCard
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer iscard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.CardType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.Amount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.CheckTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.IsPerson
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer isperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.IsDoor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Integer isdoor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uc_roomalert_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    private Long createDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.ID
     *
     * @return the value of uc_roomalert_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.ID
     *
     * @param id the value for uc_roomalert_log.ID
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.PmsCode
     *
     * @return the value of uc_roomalert_log.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getPmscode() {
        return pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.PmsCode
     *
     * @param pmscode the value for uc_roomalert_log.PmsCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setPmscode(String pmscode) {
        this.pmscode = pmscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.HotelCode
     *
     * @return the value of uc_roomalert_log.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getHotelcode() {
        return hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.HotelCode
     *
     * @param hotelcode the value for uc_roomalert_log.HotelCode
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setHotelcode(String hotelcode) {
        this.hotelcode = hotelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.RoomNo
     *
     * @return the value of uc_roomalert_log.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public String getRoomno() {
        return roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.RoomNo
     *
     * @param roomno the value for uc_roomalert_log.RoomNo
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setRoomno(String roomno) {
        this.roomno = roomno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.IsCard
     *
     * @return the value of uc_roomalert_log.IsCard
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIscard() {
        return iscard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.IsCard
     *
     * @param iscard the value for uc_roomalert_log.IsCard
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIscard(Integer iscard) {
        this.iscard = iscard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.CardType
     *
     * @return the value of uc_roomalert_log.CardType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.CardType
     *
     * @param cardtype the value for uc_roomalert_log.CardType
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCardtype(Integer cardtype) {
        this.cardtype = cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.Amount
     *
     * @return the value of uc_roomalert_log.Amount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.Amount
     *
     * @param amount the value for uc_roomalert_log.Amount
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.CheckTime
     *
     * @return the value of uc_roomalert_log.CheckTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.CheckTime
     *
     * @param checktime the value for uc_roomalert_log.CheckTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setChecktime(Long checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.IsPerson
     *
     * @return the value of uc_roomalert_log.IsPerson
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIsperson() {
        return isperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.IsPerson
     *
     * @param isperson the value for uc_roomalert_log.IsPerson
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIsperson(Integer isperson) {
        this.isperson = isperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.IsDoor
     *
     * @return the value of uc_roomalert_log.IsDoor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Integer getIsdoor() {
        return isdoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.IsDoor
     *
     * @param isdoor the value for uc_roomalert_log.IsDoor
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setIsdoor(Integer isdoor) {
        this.isdoor = isdoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uc_roomalert_log.Create_DateTime
     *
     * @return the value of uc_roomalert_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public Long getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uc_roomalert_log.Create_DateTime
     *
     * @param createDatetime the value for uc_roomalert_log.Create_DateTime
     *
     * @mbggenerated Tue Mar 13 16:31:51 CST 2018
     */
    public void setCreateDatetime(Long createDatetime) {
        this.createDatetime = createDatetime;
    }
}